name: learn-workflow-scheduled
run-name: ${{ github.actor }} - workflow scheduled
on: 
  schedule:
#  - cron: '*/5 * * * *'

jobs:
  job1:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v4
    - name: List files
      run: ls
